spring.application.name=activityservice

server.port=8082

# DataSource configuration
spring.mongodb.uri=mongodb://localhost:27017/aiactivitydb

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/