spring.application.name=aiservice

server.port=8083

# DataSource configuration
spring.mongodb.uri=mongodb://localhost:27017/AiFitnessRecommendationdb

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/