server.port=8082

# DataSource configuration
spring.mongodb.uri=${MONGODB_ACTIVITY_URI:mongodb://localhost:27017/aiactivitydb}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# kafka configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

kafka.topic.name=activity-events

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
