server.port=8083

# DataSource configuration
spring.mongodb.uri=mongodb://localhost:27017/AiFitnessRecommendationdb

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true

# kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=activity-processor-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.fitnesstracker.aiservice.model.Activity
spring.kafka.consumer.properties.spring.json.trusted.packages= "*"

kafka.topic.name=activity-events


# Gemini API keys
# Set GEMINI_URL and GEMINI_KEY as environment variables before starting the config server,
# or override these in the ai-service's local application.properties
gemini.api.url=${GEMINI_URL}
gemini.api.key=${GEMINI_KEY}