server.port=8081

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/fitness_tracker_db}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
