spring.application.name=eureka

server.port=8761

# Eureka Server should not register itself as a client
eureka.client.register-with-eureka=false

# Eureka Server does not need to fetch registry information from itself
eureka.client.fetch-registry=false